### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by opatut**

### CODE REVIEW

**Comment by svenstaro** [comment]
Not sure about this. In rust you're often expected to run rustfmt anyway and then how you format your code while writing it is pretty irrelevant. Unless you feel strongly about this I'd close the issue and recommend you write the code however you want and then run rustfmt.

**Comment by opatut** [comment]
IMO it's nicer when vim does the right indentation while writing already (indent after newline in new `{` block, backspace unindents correctly, ...). Autoformatting is good, but it's always defered at least until I save. 

But oh well, I can configure my indentation locally too. No strong opinions here. I just thought, why not use editorconfig, it's such a good invention. Of course it should complement auto formatting, not replace it. And it also works for non-rust files ;)

**Comment by opatut** [comment]
FYI:

```
$ rustfmt $(ag -l --rs); git diff --stat | tail -n1
12 files changed, 103 insertions(+), 91 deletions(-)
```
You might want to enforce proper formatting in CI ;)

**Comment by svenstaro** [comment]
Ok look, honestly I don't mind. Since it's somewhat generic might as well merge it. I don't personally use .editorconfig but I see why people might want to use it.

I don't see a need to enforce formatting via CI.

**Pull request merged**
