### PR TITLE
Add snapcraft.yaml for snap packaging

### PR DESCRIPTION
**Pull request by kaxing**
Made a yaml file to pack genact as a snap, using [snapcraft](https://snapcraft.io]).
Did a rough test, and put genact in a fully confined enviroment;
Would be nice to make more users looks much busier and still feeling safe :)

### CODE REVIEW

**Comment by zmdi998** [comment]
你很厉害，我很喜欢你的作品。大神我我是你的铁粉。

**Comment by zmdi998** [comment]
永远关注你，挺你。

**Comment by svenstaro** [comment]
Uh thanks I guess? :smile:

**Comment by zmdi998** [comment]
你猜什么我没有我明白你的意思。

**Comment by zmdi998** [comment]
大神你能指导我一些东西吗？

**Comment by kaxing** [comment]
Hi @svenstaro,

The yaml file will be used by snapcraft (packaging tool) to pack it into snap, one handy thing is to leverage the auto-build and publish [service](https://build.snapcraft.io), which also connects to github project. If you felt like to put it onto the store.

Otherwise, this yaml file could still be handy for people who want to use snap package locally, as the process will be ran in sandbox environment to avoid some security concerns, but it would be nonsense to be that panic :)

**Comment by svenstaro** [comment]
I read into this and it seems pretty cool. Thanks!

**Pull request merged**
