### PR TITLE
use multistage Dockerfile to keep image size low

### PR DESCRIPTION
**Pull request by floj**
I added some lines to the Dockerfile to utilize multi-stage builds. This reduces the image size to around ~60MB by only adding the final `genact` binary to the image.

### CODE REVIEW

**Comment by svenstaro** [comment]
That's awesome! Today I learned about multi-stage builds! However, I'm thinking we can do even better. We should probably use Alpine as the image for shipping this. Of course, Alpine uses musl so we have to build against that. Thankfully, I got you covered there. Check this Makefile [here](https://github.com/svenstaro/genact/blob/master/Makefile#L2). You should be able to use that.

The resulting binary should be universally portable and should run just fine on Alpine.

**Comment by floj** [comment]
Hey, great! I tried Alpine first, but the binary did not work due to musl, as you pointed put (the official Rust image is Debian/glibc based).
I know docker pretty well, but I hardly know anything about Rust, cargo and how to build things. ;) So thanks for helping out and hinting to the Makefile. Must have overlooked it in the first place.
I change the Dockerfile in a minute.

**Comment by floj** [comment]
Just realized when building with `--target x86_64-unknown-linux-musl`, the resulting binary is statically linked. So we can even top Alpine by using `FROM scratch`. I updated the Dockerfile accordingly.
I had to add some additional lines to install `upx` and add the `musl`-target to rust. Let me know whats your opinion on that. 😄

**Comment by svenstaro** [comment]
Great stuff.

**Pull request merged**
